### ISSUE TITLE
JavaScript Courses to be completed

### ISSUE THREAD

**Issue by onetoughcookie226** [onetoughcookie226/random-background-color#2]
## TODO

_Courses left to complete the Treehouse JavaScript Track_
- [x] jQuery Basics
- [ ] Using jQuery plugins
- [ ] Interactive web pages with js
- [x] AJAX Basics
- [x] Object Oriented JavaScript
- [ ] Node.js basics
- [ ] Build a simple Dynamic site with Node.js
- [ ] npm Basics
- [ ] express Basics
- [ ] Gulp Basics
- [ ] Angular Basics
- [ ] Mango Basics

🎉 🙆 🎊 
cc@zorancco
